DROP PROCEDURE IF EXISTS CREAR_CARTERA;
DELIMITER $
CREATE PROCEDURE CREAR_CARTERA(
	IN _ID_CARTERA INT,
    IN _FONDOS DECIMAL(10, 2),
    IN _CANT_MOVIMIENTOS INT
)
BEGIN
	INSERT INTO Cartera(ID_CARTERA, FONDOS, CANT_MOVIMIENTOS)
	VALUES (_ID_CARTERA, _FONDOS, _CANT_MOVIMIENTOS);
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS ACTUALIZAR_CARTERA;
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_CARTERA(
	IN _ID_CARTERA INT,
    IN _FONDOS DECIMAL(10, 2),
    IN _CANT_MOVIMIENTOS INT
)
BEGIN
	UPDATE Cartera SET FONDOS = _FONDOS, CANT_MOVIMIENTOS = _CANT_MOVIMIENTOS WHERE ID_CARTERA = _ID_CARTERA;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS BUSCAR_CARTERA;
DELIMITER $
CREATE PROCEDURE BUSCAR_CARTERA(
	IN _ID_CARTERA INT
)
BEGIN
	SELECT * FROM Cartera WHERE ID_CARTERA = _ID_CARTERA;
END $
DELIMITER ;
