DROP PROCEDURE IF EXISTS CREAR_NOTIFICACION;
DELIMITER $
CREATE PROCEDURE CREAR_NOTIFICACION(
	OUT _ID_NOTIFICACION INT,
    IN _TIPO VARCHAR(30),
    IN _MENSAJE VARCHAR(200),
    IN _FID_USUARIO INT
)
BEGIN
	INSERT INTO Notificacion(TIPO, MENSAJE, FID_USUARIO, REVISADA, ACTIVO)
    VALUES (_TIPO, _MENSAJE, _FID_USUARIO, FALSE, 1);
    SET _ID_NOTIFICACION = @@last_insert_id;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS ELIMINAR_NOTIFICACION;
DELIMITER $
CREATE PROCEDURE ELIMINAR_NOTIFICACION(
	IN _ID_NOTIFICACION INT
)
BEGIN
	UPDATE Notificacion SET REVISADA = TRUE WHERE ID_NOTIFICACION = _ID_NOTIFICACION;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS ACTUALIZAR_NOTIFICACION;
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_NOTIFICACION(
	IN _ID_NOTIFICACION INT,
    IN _TIPO VARCHAR(30),
    IN _MENSAJE VARCHAR(200),
    IN _FID_USUARIO INT
)
BEGIN
	UPDATE Notificacion SET TIPO = _TIPO, MENSAJE = _MENSAJE, FID_USUARIO = _FID_USUARIO WHERE ID_NOTIFICACION = _ID_NOTIFICACION;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS LISTAR_NOTIFICACIONES;
DELIMITER $
CREATE PROCEDURE LISTAR_NOTIFICACIONES(
	IN _FID_USUARIO INT
)
BEGIN
	SELECT * FROM Notificacion WHERE FID_USUARIO = _FID_USUARIO;
END $
DELIMITER ;