DROP PROCEDURE IF EXISTS CREAR_PAIS;
DELIMITER $
CREATE PROCEDURE CREAR_PAIS(
	OUT _ID_PAIS INT,
    IN _NOMBRE VARCHAR(100),
    IN _MONEDA VARCHAR(3)
)
BEGIN
	INSERT INTO PAIS(NOMBRE, MONEDA)
    VALUES (_NOMBRE, _MONEDA);
    SET _ID_PAIS = @@last_insert_id;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS BUSCAR_PAIS;
DELIMITER $
CREATE PROCEDURE BUSCAR_PAIS(
	IN _ID_PAIS INT
)
BEGIN
	SELECT * FROM PAIS WHERE ID_PAIS = _ID_PAIS;
END $
DELIMITER ;