DROP PROCEDURE IF EXISTS CREAR_USUARIO;
DELIMITER $
CREATE PROCEDURE CREAR_USUARIO(
	OUT _ID_USUARIO INT,
    IN _NOMBRE_CUENTA VARCHAR(100),
    IN _NOMBRE_PERFIL VARCHAR(100),
    IN _CORREO VARCHAR(100),
    IN _TELEFONO VARCHAR(100),
    IN _CONTRASENIA VARCHAR(100),
    IN _EDAD INT,
    IN _FECHA_NACIMIENTO DATE,
    IN _VERIFICADO TINYINT,
    IN _EXPERIENCIA_NIVEL INT,
    IN _NIVEL INT,
    IN _EXPERIENCIA INT,
    IN _FID_PAIS INT
)
BEGIN
	INSERT INTO Usuario(NOMBRE_CUENTA, NOMBRE_PERFIL, CORREO, TELEFONO,
						CONTRASENIA, EDAD, FECHA_NACIMIENTO, VERIFICADO,
                        EXPERIENCIA_NIVEL, NIVEL, EXPERIENCIA, FID_PAIS, ACTIVO)
	VALUES (_NOMBRE_CUENTA, _NOMBRE_PERFIL, _CORREO, _TELEFONO,
			_CONTRASENIA, _EDAD, _FECHA_NACIMIENTO, _VERIFICADO,
			_EXPERIENCIA_NIVEL, _NIVEL, _EXPERIENCIA, _FID_PAIS, true);
    SET _ID_USUARIO = @@last_insert_id;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS ACTUALIZAR_USUARIO;
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_USUARIO(
	IN _ID_USUARIO INT,
    IN _NOMBRE_CUENTA VARCHAR(100),
    IN _NOMBRE_PERFIL VARCHAR(100),
    IN _CORREO VARCHAR(100),
    IN _TELEFONO VARCHAR(100),
    IN _CONTRASENIA VARCHAR(100),
    IN _EDAD INT,
    IN _FECHA_NACIMIENTO DATE,
    IN _VERIFICADO TINYINT,
    IN _EXPERIENCIA_NIVEL INT,
    IN _NIVEL INT,
    IN _EXPERIENCIA INT,
    IN _FID_PAIS INT
)
BEGIN
	UPDATE Usuario SET NOMBRE_CUENTA = _NOMBRE_CUENTA, NOMBRE_PERFIL = _NOMBRE_PERFIL,
					   CORREO = _CORREO, TELEFONO = _TELEFONO, CONTRASENIA = _CONTRASENIA,
                       EDAD = _EDAD, FECHA_NACIMIENTO = _FECHA_NACIMIENTO, VERIFICADO = _VERIFICADO,
                       EXPERIENCIA_NIVEL = _EXPERIENCIA_NIVEL, NIVEL = _NIVEL, EXPERIENCIA = _EXPERIENCIA,
                       FID_PAIS = _FID_PAIS
	WHERE UID = _ID_USUARIO;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS SUSPENDER_USUARIO;
DELIMITER $
CREATE PROCEDURE SUSPENDER_USUARIO(
	IN _ID_USUARIO INT
)
BEGIN
	UPDATE Usuario SET ACTIVO = NOT ACTIVO WHERE UID = _ID_USUARIO;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS ELIMINAR_USUARIO;
DELIMITER $
CREATE PROCEDURE ELIMINAR_USUARIO(
	IN _ID_USUARIO INT
)
BEGIN
	DELETE FROM Usuario WHERE UID = _ID_USUARIO;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS LISTAR_USUARIO;
DELIMITER $
CREATE PROCEDURE LISTAR_USUARIO()
BEGIN
	SELECT * FROM Usuario;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS BUSCAR_USUARIO_X_NOMBRE_CUENTA;
DELIMITER $
CREATE PROCEDURE BUSCAR_USUARIO_X_NOMBRE_CUENTA(
	IN _nombre_cuenta VARCHAR(100)
)
BEGIN
    SELECT u.UID, u.nombre_cuenta, u.nombre_perfil, u.correo, u.telefono,
    u.contrasenia, u.edad, u.fecha_nacimiento, u.verificado, u.experiencia_nivel,
    u.experiencia, u.nivel, u.activo, u.fid_pais, p.nombre as 'nombre_pais', 
    p.fid_moneda, m.nombre as 'nombre_moneda', m.cambio_de_dolares, m.codigo as 'codigo_moneda'
    FROM Usuario u
    INNER JOIN Pais p ON p.id_pais = u.fid_pais
    INNER JOIN TipoMoneda m ON p.fid_moneda = m.id_tipo_moneda
    WHERE _nombre_cuenta LIKE nombre_cuenta;
END$