DROP PROCEDURE IF EXISTS CREAR_USUARIO;
DELIMITER $
CREATE PROCEDURE CREAR_USUARIO(
	OUT _ID_USUARIO INT,
    IN _NOMBRE_CUENTA VARCHAR(100),
    IN _NOMBRE_PERFIL VARCHAR(100),
    IN _CORREO VARCHAR(100),
    IN _TELEFONO VARCHAR(100),
    IN _CONTRASENIA VARCHAR(100),
    IN _EDAD INT,
    IN _FECHA_NACIMIENTO DATE,
    IN _VERIFICADO SMALLINT,
    IN _EXPERIENCIA_NIVEL INT,
    IN _NIVEL INT,
    IN _EXPERIENCIA INT,
    IN _FID_PAIS INT
)
BEGIN
	INSERT INTO USUARIO(NOMBRE_CUENTA, NOMBRE_PERFIL, CORREO, TELEFONO,
						CONTRASENIA, EDAD, FECHA_NACIMIENTO, VERIFICADO,
                        EXPERIENCIA_NIVEL, NIVEL, EXPERIENCIA, FID_PAIS, ACTIVO)
	VALUES (_NOMBRE_CUENTA, _NOMBRE_PERFIL, _CORREO, _TELEFONO,
			_CONTRASENIA, _EDAD, _FECHA_NACIMIENTO, _VERIFICADO,
			_EXPERIENCIA_NIVEL, _NIVEL, _EXPERIENCIA, _FID_PAIS, 1);
    SET _ID_USUARIO = @@last_insert_id;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS ACTUALIZAR_USUARIO;
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_USUARIO(
	IN _ID_USUARIO INT,
    IN _NOMBRE_CUENTA VARCHAR(100),
    IN _NOMBRE_PERFIL VARCHAR(100),
    IN _CORREO VARCHAR(100),
    IN _TELEFONO VARCHAR(100),
    IN _CONTRASENIA VARCHAR(100),
    IN _EDAD INT,
    IN _FECHA_NACIMIENTO DATE,
    IN _VERIFICADO SMALLINT,
    IN _EXPERIENCIA_NIVEL INT,
    IN _NIVEL INT,
    IN _EXPERIENCIA INT,
    IN _FID_PAIS INT
)
BEGIN
	UPDATE USUARIO SET NOMBRE_CUENTA = _NOMBRE_CUENTA, NOMBRE_PERFIL = _NOMBRE_PERFIL,
					   CORREO = _CORREO, TELEFONO = _TELEFONO, CONTRASENIA = _CONTRASENIA,
                       EDAD = _EDAD, FECHA_NACIMIENTO = _FECHA_NACIMIENTO, VERIFICADO = _VERIFICADO,
                       EXPERIENCIA_NIVEL = _EXPERIENCIA_NIVEL, NIVEL = _NIVEL, EXPERIENCIA = _EXPERIENCIA,
                       FID_PAIS = _FID_PAIS
	WHERE ID_USUARIO = _ID_USUARIO;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS SUSPENDER_USUARIO;
DELIMITER $
CREATE PROCEDURE SUSPENDER_USUARIO(
	IN _ID_USUARIO INT
)
BEGIN
	UPDATE USUARIO SET ACTIVO = NOT ACTIVO WHERE ID_USUARIO = _ID_USUARIO;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS ELIMINAR_USUARIO;
DELIMITER $
CREATE PROCEDURE ELIMINAR_USUARIO(
	IN _ID_USUARIO INT
)
BEGIN
	DELETE FROM USUARIO WHERE ID_USUARIO = _ID_USUARIO;
END $
DELIMITER ;
DROP PROCEDURE IF EXISTS LISTAR_USUARIO;
DELIMITER $
CREATE PROCEDURE LISTAR_USUARIO()
BEGIN
	SELECT * FROM USUARIO;
END $
DELIMITER ;