//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamWA.ComunidadWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.comunidad.steam.pucp.edu.pe/", ConfigurationName="ComunidadWS.ComunidadWS")]
    public interface ComunidadWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comunidad.steam.pucp.edu.pe/ComunidadWS/helloRequest", ReplyAction="http://services.comunidad.steam.pucp.edu.pe/ComunidadWS/helloResponse")]
        SteamWA.ComunidadWS.helloResponse hello(SteamWA.ComunidadWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comunidad.steam.pucp.edu.pe/ComunidadWS/helloRequest", ReplyAction="http://services.comunidad.steam.pucp.edu.pe/ComunidadWS/helloResponse")]
        System.Threading.Tasks.Task<SteamWA.ComunidadWS.helloResponse> helloAsync(SteamWA.ComunidadWS.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://services.comunidad.steam.pucp.edu.pe/", Order=0)]
        public SteamWA.ComunidadWS.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(SteamWA.ComunidadWS.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://services.comunidad.steam.pucp.edu.pe/", Order=0)]
        public SteamWA.ComunidadWS.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(SteamWA.ComunidadWS.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComunidadWSChannel : SteamWA.ComunidadWS.ComunidadWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComunidadWSClient : System.ServiceModel.ClientBase<SteamWA.ComunidadWS.ComunidadWS>, SteamWA.ComunidadWS.ComunidadWS {
        
        public ComunidadWSClient() {
        }
        
        public ComunidadWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComunidadWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComunidadWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComunidadWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SteamWA.ComunidadWS.helloResponse SteamWA.ComunidadWS.ComunidadWS.hello(SteamWA.ComunidadWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            SteamWA.ComunidadWS.helloRequest inValue = new SteamWA.ComunidadWS.helloRequest();
            inValue.Body = new SteamWA.ComunidadWS.helloRequestBody();
            inValue.Body.name = name;
            SteamWA.ComunidadWS.helloResponse retVal = ((SteamWA.ComunidadWS.ComunidadWS)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SteamWA.ComunidadWS.helloResponse> SteamWA.ComunidadWS.ComunidadWS.helloAsync(SteamWA.ComunidadWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<SteamWA.ComunidadWS.helloResponse> helloAsync(string name) {
            SteamWA.ComunidadWS.helloRequest inValue = new SteamWA.ComunidadWS.helloRequest();
            inValue.Body = new SteamWA.ComunidadWS.helloRequestBody();
            inValue.Body.name = name;
            return ((SteamWA.ComunidadWS.ComunidadWS)(this)).helloAsync(inValue);
        }
    }
}
