DROP PROCEDURE IF EXISTS CREAR_NOTIFICACION;
DROP PROCEDURE IF EXISTS ELIMINAR_NOTIFICACION;
DROP PROCEDURE IF EXISTS ACTUALIZAR_NOTIFICACION;
DROP PROCEDURE IF EXISTS LISTAR_NOTIFICACIONES;
DROP PROCEDURE IF EXISTS ELIMINAR_NOTIFICACIONES_USUARIO;
DROP PROCEDURE IF EXISTS MARCAR_NOTIFICACION_LEIDA;

DELIMITER $

CREATE PROCEDURE CREAR_NOTIFICACION(
    OUT _ID_NOTIFICACION INT,
    IN _TIPO VARCHAR(30),
    IN _MENSAJE VARCHAR(200),
    IN _FID_USUARIO INT
)
BEGIN
    INSERT INTO Notificacion (TIPO, MENSAJE, FID_USUARIO, REVISADA, ACTIVO, FECHA)
    VALUES (_TIPO, _MENSAJE, _FID_USUARIO, FALSE, TRUE, CURDATE());
    SET _ID_NOTIFICACION = LAST_INSERT_ID();
END$

CREATE PROCEDURE ELIMINAR_NOTIFICACION(
    IN _ID_NOTIFICACION INT
)
BEGIN
    UPDATE Notificacion SET ACTIVO = FALSE WHERE ID_NOTIFICACION = _ID_NOTIFICACION;
END$

CREATE PROCEDURE ACTUALIZAR_NOTIFICACION(
    IN _ID_NOTIFICACION INT,
    IN _TIPO VARCHAR(30),
    IN _MENSAJE VARCHAR(200),
    IN _FID_USUARIO INT,
    IN _REVISADA TINYINT
)
BEGIN
    UPDATE Notificacion 
    SET TIPO = _TIPO, MENSAJE = _MENSAJE, FID_USUARIO = _FID_USUARIO, REVISADA = _REVISADA
    WHERE ID_NOTIFICACION = _ID_NOTIFICACION;
END$

CREATE PROCEDURE LISTAR_NOTIFICACIONES(
    IN _FID_USUARIO INT
)
BEGIN
    SELECT * FROM Notificacion WHERE FID_USUARIO = _FID_USUARIO AND ACTIVO = TRUE ORDER BY FECHA DESC;
END$

CREATE PROCEDURE ELIMINAR_NOTIFICACIONES_USUARIO(
    IN _FID_USUARIO INT
)
BEGIN
    UPDATE Notificacion SET ACTIVO = FALSE WHERE FID_USUARIO = _FID_USUARIO;
END$

CREATE PROCEDURE MARCAR_NOTIFICACION_LEIDA(
    IN _id_notificacion INT
)
BEGIN
    UPDATE Notificacion SET REVISADA = TRUE WHERE ID_NOTIFICACION = _id_notificacion;
END$

DELIMITER ;