DROP PROCEDURE IF EXISTS BUSCAR_PALABRA;
DELIMITER $
CREATE PROCEDURE BUSCAR_PALABRA(
    IN _palabra VARCHAR(100)
)
BEGIN
    SELECT *
    FROM PalabrasProhibidas
    WHERE palabra = md5(_palabra);
END $
DELIMITER ;